### ISSUE TITLE
Typo in waives -> waivers

### ISSUE THREAD

**Issue by ggbecker** [RHSecurityCompliance/contest#13]
I think the correct word for `waiver` plural is `waivers`, isn't?

https://www.google.com/search?client=firefox-b-d&q=waiver+definition

**Comment by comps** [comment]
I don't think so, "waive" or "to waive" is also a valid verb, and reusing verbs as nouns in programming is quite common.

However I wouldn't be against `waivers` either (with some more code changes).

**Comment by comps** [comment]
And in another project, we've been using `waives` for years and `waivers` was never mentioned in any documentation, discussions or issue trackers for this project until the issue you filed. But like I said, I agree with `waivers`. :)

I can file a PR for this change eventually.
