### ISSUE TITLE
allow matching on architecture as well

### ISSUE THREAD

**Issue by vojtapolasek** [RHSecurityCompliance/contest#58]
Currently, afaik we can match on RHEL version and scap-security-guide package version. Sometimes, a rule fails only on certain architecture.
Please add possibility to match the architecture.
Example productization issue: https://github.com/ComplianceAsCode/content/issues/10938

**Comment by comps** [comment]
Untested yet, but should work: https://github.com/RHSecurityCompliance/contest/pull/59
