### ISSUE TITLE
Install additional packages as test setup

### ISSUE THREAD

**Issue by mildas** [RHSecurityCompliance/contest#90]
Content has several rules that depend on specific package installed. If such package is not installed, a rule is evaluated as `notapplicable`. The problem is when the package is installed during remediation phase. The `notapplicable` rules then becomes applicable and fails as the configuration has not been remediated.

Install known problematic packages (tmux, postfix, firewalld, etc.) as a test setup - via `main.fmf` or new `conf/` function.

**Comment by comps** [comment]
Note that `main.fmf` probably doesn't make sense for anything VM-based - we really want to install these in the VM guest, not on the host.

**Comment by comps** [comment]
@mildas Is this still relevant?

* We do double remediation for `oscap xccdf eval --remediate`
* OAA should have added these to `%packages` in the background
* ImageBuilder should have generated relevant `[[packages]]`
* Ansible - I don't know

**Comment by mildas** [comment]
Not relevant anymore, closing
